### ISSUE TITLE
BUG: 0.9.5 - Have to add ./ to path

### ISSUE THREAD

**Issue by davidosomething** [csumpter/restic-docker#1]
https://github.com/csumpter/restic-docker/blob/400db12cfd2a2fcc794fa495107a5c925230c01b/Dockerfile#L18

Since you copy the files to ./ (HOME?) you have to add ./ to the PATH to execute entrypoint.sh
OR run entrypoint with full path (and all sourced scripts should reference the correct filepath)

**Comment by davidosomething** [comment]
fix in #2

**Comment by csumpter** [comment]
Fixed with the merge of #2.
